// Hand-written type declarations for the wasm-bindgen bindings generated by
// `scripts/build-wasm.sh` (crucible_client_wasm.js / .d.ts / _bg.wasm).
//
// The generated files are gitignored build artifacts, so this minimal shim is
// committed to keep `npm run typecheck` (and IDEs) green without a Rust
// toolchain. Running `npm run wasm` overwrites this file with the full
// generated declarations; the signatures below mirror them exactly.

export function sim_version(): string;
export function map_hq_json(seed: number): string;
export function replay_frame(replay_json: string, tick: number): string;
export function replay_meta(replay_json: string): string;
export function replay_result(replay_json: string): string;
export function replay_snapshot_json(replay_json: string, tick: number): string;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
}

export declare function __wbg_init(input?: RequestInfo | URL): Promise<InitOutput>;
export default __wbg_init;
