// Pure-JS fallback for the wasm-bindgen module generated by
// `scripts/build-wasm.sh` (crucible_client_wasm.js / _bg.wasm).
//
// WHY THIS EXISTS: the generated bindings are build artifacts, but Vite's
// import analysis needs `./crucible_client_wasm` to RESOLVE at transform
// time — a .d.ts alone satisfies tsc, not the dev server. This committed
// fallback keeps the app booting in environments without a Rust toolchain.
//
// NOTE: plain JavaScript only — this file is served to the browser as-is
// (esbuild does not strip TypeScript from .js files).
//
// The replay functions genuinely require the deterministic Rust sim (a
// replay is just {map_seed, config, commands}), so they throw a clear,
// actionable error instead of pretending. Running `npm run wasm` overwrites
// this file with the real bindings and everything works.

class ReplayEngineUnavailableError extends Error {
  constructor() {
    super(
      "Replay engine not compiled — run `npm run wasm` in client/ (requires a Rust toolchain with the wasm32 target).",
    );
    this.name = "ReplayEngineUnavailableError";
  }
}

export function sim_version() {
  return "crucible-sim js-fallback (no wasm engine)";
}

export function map_hq_json(_seed) {
  throw new ReplayEngineUnavailableError();
}

export function replay_frame(_replay_json, _tick) {
  throw new ReplayEngineUnavailableError();
}

export function replay_meta(_replay_json) {
  throw new ReplayEngineUnavailableError();
}

export function replay_result(_replay_json) {
  throw new ReplayEngineUnavailableError();
}

export function replay_snapshot_json(_replay_json, _tick) {
  throw new ReplayEngineUnavailableError();
}

// The fallback never instantiates the placeholder _bg.wasm; resolve with an
// InitOutput-shaped object so `wasmInit()` callers proceed normally and the
// per-call errors above surface in the UI instead.
export async function __wbg_init(_input) {
  return { memory: new WebAssembly.Memory({ initial: 1 }) };
}

export default __wbg_init;
